// <auto-generated />
using System;
using Dictionary.Dal.Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dictiomary.Dal.Migrations
{
    [DbContext(typeof(DictionaryDbContext))]
    [Migration("20220925141712_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dictionary.Dal.Models.EnglishWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Englishes");
                });

            modelBuilder.Entity("Dictionary.Dal.Models.UkranianWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Word")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ukranians");
                });

            modelBuilder.Entity("Dictionary.Dal.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EngId")
                        .HasColumnType("int");

                    b.Property<int?>("EnglishWordId")
                        .HasColumnType("int");

                    b.Property<int>("UkrId")
                        .HasColumnType("int");

                    b.Property<int?>("UkranianWordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnglishWordId");

                    b.HasIndex("UkranianWordId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Dictionary.Dal.Models.Word", b =>
                {
                    b.HasOne("Dictionary.Dal.Models.EnglishWord", "EnglishWord")
                        .WithMany("UkranianWords")
                        .HasForeignKey("EnglishWordId");

                    b.HasOne("Dictionary.Dal.Models.UkranianWord", "UkranianWord")
                        .WithMany("EnglishWords")
                        .HasForeignKey("UkranianWordId");

                    b.Navigation("EnglishWord");

                    b.Navigation("UkranianWord");
                });

            modelBuilder.Entity("Dictionary.Dal.Models.EnglishWord", b =>
                {
                    b.Navigation("UkranianWords");
                });

            modelBuilder.Entity("Dictionary.Dal.Models.UkranianWord", b =>
                {
                    b.Navigation("EnglishWords");
                });
#pragma warning restore 612, 618
        }
    }
}
